x-wharfmap:
  backgroundColor: "#f5f5f583"
  backgroundBorderColor: "#cccccc"
  backgroundBorderWidth: 2
  networks:
    tmdb-net:
      color: "#EBDBD1"          # Light blue for frontend network
      border-color: "#DDCEBC"
      border-width: "2px"
      border-style: "solid"
    spark-net:
      color: "#acbde5"          # Light yellow for spark network
      border-color: "#8bb4df"
      border-width: "2px"
      border-style: "solid"
  conditions:
    service_started:
      stroke-width: "2px"
      stroke-dasharray: "5 5"
    service_completed_successfully:
      stroke-width: "2px"
      stroke-dasharray: "0"
services:
  redis:
    image: redis:7-alpine
    container_name: tmdb-redis
    networks:
      - spark-net
      - tmdb-net
    ports:
      - "6379:6379"
    x-wharfmap:
      color: "#D82C20"           # Fill/background color
      border-color: "#7A0C00"    # Border color
      border-width: "3px"        # Border thickness (with units)
      border-style: "solid"     # Border style: "solid" or "dashed"

  spark-master:
    build:
      context: ./spark
    container_name: spark-master
    networks:
      - spark-net
    depends_on:
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "7077:7077"
      - "8080:8080"
    command: /bin/bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    volumes:
      - ./spark:/spark
    x-wharfmap:
      color: "#F69824"           # Fill/background color
      border-color: "#E4682A"    # Border color
      border-width: "3px"        # Border thickness (with units)
      border-style: "solid"     # Border style: "solid" or "dashed"

  spark-worker:
    build:
      context: ./spark
    # container_name: spark-worker
    networks:
      - spark-net
    depends_on:
      spark-master:
        condition: service_started
    command: /bin/bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 --cores 4 --memory 4g && tail -f /dev/null"
    volumes:
      - ./spark:/spark
    x-wharfmap:
      color: "#CC2336"           # Fill/background color
      border-color: "#A22160"    # Border color
      border-width: "3px"        # Border thickness (with units)
      border-style: "solid"     # Border style: "solid" or "dashed"
  
  job-runner:
    build:
      context: ./spark
    container_name: job-runner
    networks:
      - spark-net
    environment:
      # - dataset=small
      - dataset=normal
    depends_on:
      spark-worker:
        condition: service_started
    volumes:
      - ./spark:/spark
    command: /bin/bash -c "\
      /opt/spark/bin/spark-submit --master spark://spark-master:7077   --executor-memory 4g   --total-executor-cores 4   --conf spark.sql.shuffle.partitions=200  /spark/jobs/train_als.py && \ 
      python3 /spark/jobs/load_data.py"
    x-wharfmap:
      color: "#C78DAF"           # Fill/background color
      border-color: "#797497"    # Border color
      border-width: "3px"        # Border thickness (with units)
      border-style: "solid"     # Border style: "solid" or "dashed"

  backend:
    build:
      context: ./backend
    container_name: tmdb-backend
    networks:
      - tmdb-net
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1  
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      job-runner:
        condition: service_completed_successfully
      spark-master:
        condition: service_started
      spark-worker:
        condition: service_started
      redis:
        condition: service_started
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    x-wharfmap:
      color: "#479387"           # Fill/background color
      border-color: "#2c5952"    # Border color
      border-width: "3px"        # Border thickness (with units)
      border-style: "solid"     # Border style: "solid" or "dashed"

  frontend:
    build:
      context: ./frontend/nuxt/tmdb-frontend
    container_name: tmdb-frontend
    networks:
      - tmdb-net
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    x-wharfmap:
      color: "#42b883"           # Fill/background color
      border-color: "#35495e"    # Border color
      border-width: "3px"        # Border thickness (with units)
      border-style: "solid"     # Border style: "solid" or "dashed"

networks:
  tmdb-net:
    driver: bridge
  spark-net:
    driver: bridge